##
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
##

version: 2.1

##
# Orbs
##

orbs:
  deploy: oddhill/deploy@0.0.2
  drupal: oddhill/drupal-8@0.0.5
  node: circleci/node@4.1.0
  php: circleci/php@1.1.0

##
# Executors
##

executors:
  node:
    docker:
      - image: cimg/node:14.15.4
  php:
    docker:
      - image: cimg/php:7.4.14

##
# Commands
##

commands:
  install-node-dependencies:
    description: Installing theme dependencies
    parameters:
      cache-version:
        default: v1
        description: >-
          Change the default cache version if you need to clear the cache for any
          reason.
        type: string
      theme-name:
        default: oddbaby
        type: string
    steps:
      - node/install-packages:
          app-dir: ./public/themes/custom/<<parameters.theme-name>>
          pkg-manager: yarn
          cache-key: yarn.lock

  install-composer-dependencies:
    description: Install project dependencies
    parameters:
      cache-version:
        default: v1
        description: >-
          Change the default cache version if you need to clear the cache for any
          reason.
        type: string
    steps:
      - restore_cache:
          keys:
            - <<parameters.cache-version>>-composer-{{ checksum "composer.lock" }}
      - run:
          name: Updating composer
          command: sudo composer self-update --2
      - run:
          name: Installing composer dependencies
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: <<parameters.cache-version>>-composer-{{ checksum "composer.lock" }}
          paths:
            - drush/contrib
            - public/core
            - public/libraries
            - public/modules/contrib
            - public/profiles/contrib
            - public/themes/contrib
            - vendor

##
# Jobs
##

jobs:

  # Install project dependencies
  project_dependencies:
    executor: php
    steps:
      - checkout
      - install-composer-dependencies

  # Check coding standards with PHPCS
  project_phpcs:
    executor: php
    steps:
      - checkout
      - install-composer-dependencies
      - drupal/phpcs

  # Deploy to testing
  deploy_testing:
    executor: php
    steps:
      - checkout
      - install-composer-dependencies
      - deploy/ssh:
          hostname: stage.example.com
          remote-path: /var/www/stage.example.com
          user: root
      - drupal/drush-post-deploy:
          alias: testing

  # Deploy to production
  deploy_production:
    executor: php
    steps:
      - checkout
      - install-composer-dependencies
      - deploy/ssh:
          hostname: www.example.com
          remote-path: /var/www/www.example.com
          user: root
      - drupal/drush-post-deploy:
          alias: production

##
# Workflows
##

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - project_dependencies
      - project_phpcs:
          requires:
            - dependencies
      - deploy_testing:
          requires:
            - phpcs
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - phpcs
          filters:
            branches:
              only: master
