name: Test installation

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MARIADB_DATABASE: drupal
          MARIADB_ROOT_PASSWORD: password
          MARIADB_USER: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: gd, mbstring, pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Drupal
        run: vendor/bin/drush site:install oddprofile --db-url=mysql://root:password@127.0.0.1:3306/drupal
