name: Test installation

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: ['master']

  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MARIADB_DATABASE: drupal
          MARIADB_ROOT_PASSWORD: password
          MARIADB_USER: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd, mbstring, pdo, pdo_mysql

      - name: Set up PNPM
        uses: pnpm/action-setup@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Install Drupal
        run: vendor/bin/drush site:install oddprofile --db-url=mysql://root:password@127.0.0.1:3306/drupal

      - name: Run E2E tests
        run: pnpm test:dev
