name: Test installation

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: php:8.2-apache
    services:
      mariadb:
        image: mariadb:11
        env:
          MARIADB_ROOT_PASSWORD: password
        volumes:
          - ./:/var/www/html
    steps:
      - uses: actions/checkout@v4
      - name: Log directory contents
        run: |
          pwd
          ls -al
      - uses: php-actions/composer@v6
        with:
          container_workdir: /__w/drupal-starter-kit/drupal-starter-kit
          php_version: 8.2
          working_dir: /__w/drupal-starter-kit/drupal-starter-kit
      - name: Test site installation
        run: vendor/bin/drush site:install oddprofile --db-url=mysql://root@127.0.0.1:3306/drupal
