name: Test installation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: php:8.2-apache
    services:
      mariadb:
        image: mariadb:11
        volumes:
          - ./:/var/www/html
    steps:
      - uses: actions/checkout@v3
      - name: Test site installation
        run: vendor/bin/drush site:install oddprofile --db-url=mysql://root@127.0.0.1:3306/drupal
